### PR TITLE
V1.4.0

### PR DESCRIPTION
**Pull request by sanderland**

### CODE REVIEW

**Comment by sanderland** [comment]
@kaorahi could you add the 6 todo entries (and possibly update 'teaching settings' to 'teaching & analysis settings') ? Thanks!

**Comment by kaorahi** [comment]
For translation...

What are "requirements" in "Engine missing DLL" message? Does it mean the file `requirements.txt`? I cannot find an explicit "requirements" section in the documents at a glance.

katrain/i18n/locales/en/LC_MESSAGES/katrain.po
~~~
#. TODO
msgid "Engine missing DLL"
msgstr ""
"Failed to start KataGo due to missing DLL. Check the requirements, or try "
"running the binary by itself for details. "
~~~

**Comment by sanderland** [comment]
> For translation...
> 
> What are "requirements" in "Engine missing DLL" message? Does it mean the file `requirements.txt`? I cannot find an explicit "requirements" section in the documents at a glance.
> 
> katrain/i18n/locales/en/LC_MESSAGES/katrain.po
> 
> ```
> #. TODO
> msgid "Engine missing DLL"
> msgstr ""
> "Failed to start KataGo due to missing DLL. Check the requirements, or try "
> "running the binary by itself for details. "
> ```

this would usually be installing CUDA for that particular binary - meaning requirements in the katago documentation.

**Comment by kaorahi** [comment]
ic. thx!

**Pull request merged**
