### PR TITLE
rank_consistency

### PR DESCRIPTION
**Pull request by bale-go**
A stand-alone script to calculate the overall rank of the total game and parts of it (opening, early middle, late middle game, endgame).
The function expects a list containing the number of legal moves, a list with the policy rank of the move, a list a list with the policy value of the move, and the length of segments (e.g. 50 moves).
It returns a list with the overall rank in kyu and ranks of consecutive segments.
3 examples are included.

### CODE REVIEW

**Comment by sanderland** [comment]
interesting work, but it doesn't really fit in for now, so i'll leave it in PR until we figure that out.

**Comment by bale-go** [comment]
3 non random parsed files and a spreadsheet to show the calculations.
Some changes in the script.

**Comment by bale-go** [comment]
Switched from median to average where the best and worst 20% of ranks were removed.
More consistent estimation of higher ranks are possible now.

**Comment by Satoshi-Yoda** [comment]
Looks like very interesting work :3

**Comment by sanderland** [comment]
> Looks like very interesting work :3

See issue #44 for a very long discussion :)

**Pull request closed without merging**
