### PR TITLE
Show total point loss

### PR DESCRIPTION
**Pull request by pdeblanc**
This adds a "Total Points Lost" value to the sidebar, i.e. the total loss of all moves by the given player up to the current point in the game.

This feature can quickly give the user a rough idea of how well each side played in the game, and also the relative weight of total mistakes in the opening, midgame, and endgame.

### CODE REVIEW

**Comment by sanderland** [comment]
Hmm, interesting idea, but not sure it warrants using such prime real estate in the UI. 
Maybe a little popup under analysis? This could then contain all the advanced stats for both players we might want to add.

**Comment by pdeblanc** [comment]
> Hmm, interesting idea, but not sure it warrants using such prime real estate in the UI.
> Maybe a little popup under analysis? This could then contain all the advanced stats for both players we might want to add.

By popup, do you a tooltip or modal? Or do you mean a collapsible section with a `>>` / `<<` button in the corner?

This calculation depends on which node is currently selected (since the sum does not include future nodes), so I feel that it should be displayed or accessed somewhere lower in the sidebar than the node selector.

**Comment by sanderland** [comment]
I meant a modal. I'm not sure the current node is that relevant, I see this more as a feature for a full-game overview  (at most identifying the branch that's selected)
mistakes in opening, middle, endgame for example, maybe even compared with stats for different ranks.

Overall the number is highly related to the current score and I don't think it belongs in the sidebar, sorry.

**Comment by sanderland** [comment]
Github closed this because 1.7.3 was merged, oops!

**Pull request closed without merging**
