### PR TITLE
Blended territory display

### PR DESCRIPTION
**Pull request by jacobm-tech**
This implements a blended territory display and ownership marks on stones as discussed in issue #555. The implementation works for expected player territory and loss in teaching games.

### CODE REVIEW

**Comment by sanderland** [comment]
Very nice. Let's aim this at 1.12 as it's quite a major change.

**Comment by jacobm-tech** [comment]
I resolved the conflict (whitespace) with the 1.12 branch.

**Comment by sanderland** [comment]
Please `black -l 120` before merge

**Comment by sanderland** [comment]
THEMES.md probably could use an update as well, if you want

**Comment by jacobm-tech** [comment]
Reformat is done. I will take a look at the documentation and screenshots.

**Comment by jacobm-tech** [comment]
Committed documentation for territory styles and themes. I still need one more commit to clean up variable names a little, then I'll be ready for merge. Also, the links for images currently point to my fork, they will need to be changed when merging.

**Comment by jacobm-tech** [comment]
Ready for review.

**Comment by sanderland** [comment]
Looks really good! Could you add a screenshot of the "blended+weak" style? I feel that may be my default, but will poll to see what do to :)

**Comment by jacobm-tech** [comment]
I changed the table in themes doc to add 4th screenshot.

**Comment by sanderland** [comment]
Excellent. Thanks for this great contribution!

**Pull request merged**
