### PR TITLE
Playname display issue 

### PR DESCRIPTION
**Pull request by xiaoyifang**
resolve the  the issue in
https://github.com/sanderland/katrain/issues/368

### CODE REVIEW

**Comment by sanderland** [comment]
It is meant to prevent re-loading the "Human (Normal game)" etc. from loading back into it, so removing it completely is wrong.

**Comment by xiaoyifang** [comment]
you mean the following display is intented when loaded the sgf again.
image

**Comment by xiaoyifang** [comment]
the current version does not show the player name. A/B ,you can test the attached sgf file

**Comment by sanderland** [comment]
See discussion/commit in #368

**Comment by xiaoyifang** [comment]
> meant to prevent loading e.g. "Human (teaching game)" or "AI (Calibrated rank)" as the player name

I think ,the PL property in the sgf file is too useful to contain any specific display logic.
can we use a custom defined property in the sgf file to determine whether ""Human (teaching game)" or "AI (Calibrated rank)" should be displayed.

though i think even display name is "Human (teaching game)" or "AI (Calibrated rank)" will not cause any problem.

**Comment by sanderland** [comment]
It just contains some characters that are invisible, sabaki for example does fine in displaying it.
Will change the issue title to using a specific tag and consider it for later versions.

**Pull request closed without merging**
