### PR TITLE
Restore shaded territory display as a themeable option

### PR DESCRIPTION
**Pull request by milescrawford**
See https://github.com/sanderland/katrain/issues/555 for discussion.

This restores the ability to use katago/lizzie/etc style for territory display.

It also updates the docs to reflect the fact that `OWNERSHIP_MAX_ALPHA` is now replaced with full color/alpha specs.

Example display with my theme:
Screen Shot 2022-12-02 at 1 01 29 PM

### CODE REVIEW

**Comment by milescrawford** [comment]
@jacobm-tech @sanderland 

Updated docs to restore the shaded style. Because I fixed the screenshot links to be relative, they don't look good in the PR preview, but you can see the full version here:
https://github.com/milescrawford/katrain/blob/shaded-style/THEMES.md

Thanks for having a look.

**Comment by sanderland** [comment]
Some code looks missing?

**Comment by milescrawford** [comment]
Actually I don't think so!

Blended is the default and the only difference from blended is this one
filter line.

If you want a more explicit distinction in the code I could do that, but it
would only be cosmetic.

**Comment by sanderland** [comment]
> Actually I don't think so! Blended is the default and the only difference from blended is this one filter line. If you want a more explicit distinction in the code I could do that, but it would only be cosmetic.

Aha, sorry, it's getting a bit complicated ^_^''

**Pull request merged**
