### PR TITLE
1.8.0

### PR DESCRIPTION
**Pull request by sanderland**
- [x] korean
- [x] simplified chinese
- [x] traditional chinese
- [x] japanese
- [x] german
- [x] french
- [x] russian

### CODE REVIEW

**Comment by sanderland** [comment]
@Tony-Liou @kaorahi @Dontbtme @Satoshi-Yoda this should be ready for translation now.

**Comment by sanderland** [comment]
@Harleqin @Tony-Liou @kaorahi @Dontbtme @Satoshi-Yoda this should be ready for translation now.

**Comment by Tony-Liou** [comment]
@sanderland I'll send a PR to 1.8.0 branch when I finish the translation:smiley:

**Comment by sanderland** [comment]
For translators, here are some screenshots of the new strings in context.
image
image
image

**Pull request merged**
