### PR TITLE
support long "Path to Katago executable"

### PR DESCRIPTION
**Pull request by rexl2018**
so that ssh to remote host can work

### CODE REVIEW

**Comment by sanderland** [comment]
What isn't working? shlex split is very OS dependent

**Comment by rexl2018** [comment]
For scenario we want to ssh to remote host, we always have long command which includes spaces, for example, my command to run in colab is: "c:/Tools/putty/plink.exe -load ngrok -l root -pw password -batch 'ls;export LD_LIBRARY_PATH=/usr/lib64-nvidia;/content/runkata/katago analysis -model /content/runkata/20b.bin.gz -config /content/runkata/analysis_example.cfg -analysis-threads 12'". With current implementation, it doesn't work.

**Comment by sanderland** [comment]
I'll do some tests and get back to you. Could you try quoting the arguments with spaces?

**Comment by sanderland** [comment]
will test in 1.3.5

**Comment by sanderland** [comment]
reverted as it breaks katrain on linux @rexl2018

**Pull request merged**
