### PR TITLE
Japanese translation for v1.3.1

### PR DESCRIPTION
**Pull request by kaorahi**
I added Japanese translation as Katrain is so interesting :)
Please let me know if there are any problems.

### CODE REVIEW

**Comment by sanderland** [comment]
Awesome work, making a v1.3.2 branch to fast-track your changes to release

**Comment by sanderland** [comment]
@kaorahi I noticed that you didn't translate the AI names - was this on purpose? Ones like 'Policy Weighted' are often hard to translate, but ones like "Territorial Style" should be pretty clear, no?

**Comment by kaorahi** [comment]
I thought the original names will be convenient for international communications. But I noticed one can confirm the English names easily by switching the language. So I translated them in the additional PR.

**Comment by sanderland** [comment]
Thanks! all the other languages have (sometimes very creative!) translations of the names. 
There'll probably be some confusion with the google translated manual, but I think it's fine if we reach 90% comprehension for people with no English.

**Pull request merged**
